# Generated by Django 5.1.5 on 2026-01-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='イベント名')),
                ('description', models.TextField(verbose_name='説明')),
                ('category', models.CharField(choices=[('concert', 'コンサート・ライブ'), ('sports', 'スポーツ観戦'), ('theater', '演劇・舞台'), ('festival', 'フェス・野外イベント'), ('online', 'オンラインイベント')], max_length=20, verbose_name='カテゴリ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images/', verbose_name='イベント画像')),
                ('start_datetime', models.DateTimeField(verbose_name='開始日時')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='終了日時')),
                ('status', models.CharField(choices=[('draft', '販売準備中'), ('on_sale', '販売中'), ('paused', '販売一時停止'), ('sold_out', '売り切れ'), ('closed', '販売終了'), ('cancelled', '開催中止')], default='draft', max_length=20, verbose_name='ステータス')),
                ('is_public', models.BooleanField(default=False, verbose_name='公開')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'イベント',
                'verbose_name_plural': 'イベント',
                'db_table': 'events',
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='種別名')),
                ('type', models.CharField(choices=[('reserved', '座席指定'), ('free', '自由席')], max_length=20, verbose_name='タイプ')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='価格')),
                ('total_quantity', models.IntegerField(verbose_name='総販売枚数')),
                ('sold_quantity', models.IntegerField(default=0, verbose_name='販売済枚数')),
                ('sale_start', models.DateTimeField(blank=True, null=True, verbose_name='販売開始日時')),
                ('sale_end', models.DateTimeField(blank=True, null=True, verbose_name='販売終了日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'チケット種別',
                'verbose_name_plural': 'チケット種別',
                'db_table': 'ticket_types',
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='会場名')),
                ('address', models.TextField(verbose_name='住所')),
                ('capacity', models.IntegerField(verbose_name='収容人数')),
                ('seat_map_image', models.ImageField(blank=True, null=True, upload_to='venue_seat_maps/', verbose_name='座席図')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '会場',
                'verbose_name_plural': '会場',
                'db_table': 'venues',
            },
        ),
    ]
