# Generated by Django 5.1.5 on 2026-01-11 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
        ('orders', '0001_initial'),
        ('seats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='ticket_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='events.tickettype'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='seats.seat'),
        ),
        migrations.CreateModel(
            name='Cancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='キャンセル理由')),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='返金額')),
                ('status', models.CharField(choices=[('requested', '申請中'), ('approved', '承認済み'), ('rejected', '却下'), ('processed', '処理完了')], default='requested', max_length=20, verbose_name='ステータス')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='申請日時')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='処理日時')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation', to='orders.order')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_cancellations', to=settings.AUTH_USER_MODEL, verbose_name='処理者')),
            ],
            options={
                'db_table': 'cancellations',
                'ordering': ['-requested_at'],
            },
        ),
    ]
