# Generated by Django 5.1.5 on 2026-01-11 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(max_length=50, verbose_name='ブロック')),
                ('row', models.CharField(max_length=10, verbose_name='列')),
                ('number', models.CharField(max_length=10, verbose_name='番号')),
                ('seat_type', models.CharField(choices=[('S', 'S席'), ('A', 'A席'), ('B', 'B席')], max_length=1, verbose_name='座席種別')),
                ('status', models.CharField(choices=[('available', '空席'), ('reserved', '予約中'), ('sold', '売約済')], default='available', max_length=20, verbose_name='ステータス')),
                ('reserved_at', models.DateTimeField(blank=True, null=True, verbose_name='仮予約日時')),
                ('version', models.IntegerField(default=0, verbose_name='バージョン')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('reserved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_seats', to=settings.AUTH_USER_MODEL, verbose_name='仮予約者')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='events.venue', verbose_name='会場')),
            ],
            options={
                'verbose_name': '座席',
                'verbose_name_plural': '座席',
                'db_table': 'seats',
                'indexes': [models.Index(fields=['venue', 'status'], name='idx_seats_venue_status'), models.Index(fields=['status', 'reserved_at'], name='idx_seats_status_reserved_at')],
                'unique_together': {('venue', 'block', 'row', 'number')},
            },
        ),
    ]
