# Generated by Django 4.2.7 on 2026-01-11 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gate', models.CharField(max_length=50, verbose_name='ゲート')),
                ('entered_at', models.DateTimeField(auto_now_add=True, verbose_name='入場日時')),
                ('scanned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanned_entries', to=settings.AUTH_USER_MODEL, verbose_name='スキャンスタッフ')),
            ],
            options={
                'verbose_name': '入場記録',
                'verbose_name_plural': '入場記録',
                'db_table': 'entries',
                'ordering': ['-entered_at'],
            },
        ),
    ]
