# Generated by Django 4.2.7 on 2026-01-11 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='tickets.ticket', verbose_name='チケット'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['ticket'], name='idx_entries_ticket'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['entered_at'], name='idx_entries_entered_at'),
        ),
    ]
