# Generated by Django 5.1.5 on 2026-01-11 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=200, verbose_name='組織名')),
                ('role', models.CharField(choices=[('admin', '管理者'), ('staff', 'スタッフ')], default='staff', max_length=20, verbose_name='権限')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='連絡先メール')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='連絡先電話')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '主催者',
                'verbose_name_plural': '主催者',
                'db_table': 'organizers',
            },
        ),
    ]
