# Generated by Django 4.2.7 on 2026-01-11 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('seats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=16, unique=True, verbose_name='チケット番号')),
                ('qr_code', models.ImageField(blank=True, upload_to='tickets/qr_codes/', verbose_name='QRコード')),
                ('status', models.CharField(choices=[('valid', '有効'), ('used', '使用済み'), ('cancelled', 'キャンセル済み')], default='valid', max_length=20, verbose_name='ステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='発行日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='orders.order', verbose_name='注文')),
                ('seat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='seats.seat', verbose_name='座席')),
            ],
            options={
                'verbose_name': 'チケット',
                'verbose_name_plural': 'チケット',
                'db_table': 'tickets',
                'indexes': [models.Index(fields=['ticket_number'], name='idx_tickets_ticket_number'), models.Index(fields=['order'], name='idx_tickets_order'), models.Index(fields=['status'], name='idx_tickets_status')],
            },
        ),
    ]
